name: Test
on:
  - push
  - pull_request
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        nim-version:
          - stable
          - 1.6.20
        chronos:
          - ''
          - '-d:asyncBackend=chronos'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ matrix.chronos }}
        run: |
          nimble install chronos -y
          echo 'requires "chronos"' >> asyncpools.nimble
      - run: nimble test -y ${{ matrix.chronos }}
